import type { Driver, Load } from "./types";
import { lngLatToSvg } from "./geo-bridge";

/** Minutes from “now” at app start — used to seed deadlines */
const now = Date.now();

export const FLEET_NAME = "NorthStar Freight";

/** Arizona & nearby — SVG map points from WGS84 via geo-bridge */
const AZ = {
  phx: lngLatToSvg(-112.074, 33.448),
  tuc: lngLatToSvg(-110.975, 32.223),
  mesa: lngLatToSvg(-111.832, 33.416),
  flag: lngLatToSvg(-111.651, 35.198),
  yuma: lngLatToSvg(-114.628, 32.693),
  king: lngLatToSvg(-114.053, 35.189),
  gil: lngLatToSvg(-111.79, 33.352),
  nog: lngLatToSvg(-110.942, 31.34),
  prescott: lngLatToSvg(-112.469, 34.54),
} as const;

/** 5 open loads — Arizona-centric lanes for demo / testing */
export const LOADS: Load[] = [
  {
    id: "L-1001",
    origin: "Phoenix, AZ",
    destination: "Tucson, AZ",
    equipment: "dry_van",
    revenue: 4200,
    pickupDeadline: now + 55 * 60 * 1000,
    pickupX: Math.round(AZ.phx.x),
    pickupY: Math.round(AZ.phx.y),
  },
  {
    id: "L-1002",
    origin: "Mesa, AZ",
    destination: "Flagstaff, AZ",
    equipment: "reefer",
    revenue: 5100,
    pickupDeadline: now + 3.2 * 60 * 60 * 1000,
    pickupX: Math.round(AZ.mesa.x),
    pickupY: Math.round(AZ.mesa.y),
  },
  {
    id: "L-1003",
    origin: "Tucson, AZ",
    destination: "Yuma, AZ",
    equipment: "flatbed",
    revenue: 3800,
    pickupDeadline: now + 4.1 * 60 * 60 * 1000,
    pickupX: Math.round(AZ.tuc.x),
    pickupY: Math.round(AZ.tuc.y),
  },
  {
    id: "L-1004",
    origin: "Gilbert, AZ",
    destination: "Nogales, AZ",
    equipment: "reefer",
    revenue: 4400,
    pickupDeadline: now + 5 * 60 * 60 * 1000,
    pickupX: Math.round(AZ.gil.x),
    pickupY: Math.round(AZ.gil.y),
  },
  {
    id: "L-1005",
    origin: "Prescott, AZ",
    destination: "Las Vegas, NV",
    equipment: "dry_van",
    revenue: 2900,
    pickupDeadline: now + 8 * 60 * 60 * 1000,
    pickupX: Math.round(AZ.prescott.x),
    pickupY: Math.round(AZ.prescott.y),
  },
];

/** 15 drivers — clustered in / near Arizona for map + scoring demos */
export const DRIVERS: Driver[] = [
  {
    id: "d1",
    name: "Marcus Chen",
    initials: "MC",
    x: 228,
    y: 398,
    ringStatus: "available",
    equipment: "dry_van",
    truckLabel: "Freightliner Cascadia · Dry",
    hosRemainingHours: 9.5,
    hosMaxHours: 11,
    laneHistoryCount: 42,
    costPerMile: 1.82,
    laneFamiliarity: 88,
  },
  {
    id: "d2",
    name: "Sarah Okonkwo",
    initials: "SO",
    x: 238,
    y: 425,
    ringStatus: "en_route",
    equipment: "reefer",
    truckLabel: "Kenworth T680 · Reefer",
    hosRemainingHours: 6.2,
    hosMaxHours: 11,
    laneHistoryCount: 31,
    costPerMile: 1.95,
    laneFamiliarity: 72,
    currentLoadEndingInHours: 2.1,
    enRoutePath: [
      { x: Math.round(AZ.tuc.x), y: Math.round(AZ.tuc.y) },
      { x: 232, y: 412 },
      { x: Math.round(AZ.phx.x), y: Math.round(AZ.phx.y) },
    ],
  },
  {
    id: "d3",
    name: "James Rivera",
    initials: "JR",
    x: 218,
    y: 418,
    ringStatus: "constrained",
    equipment: "dry_van",
    truckLabel: "Volvo VNL · Dry",
    hosRemainingHours: 2.4,
    hosMaxHours: 11,
    laneHistoryCount: 19,
    costPerMile: 1.78,
    laneFamiliarity: 61,
  },
  {
    id: "d4",
    name: "Elena Petrov",
    initials: "EP",
    x: 248,
    y: 438,
    ringStatus: "off_duty",
    equipment: "dry_van",
    truckLabel: "Peterbilt 579 · Dry",
    hosRemainingHours: 0,
    hosMaxHours: 11,
    laneHistoryCount: 54,
    costPerMile: 1.71,
    laneFamiliarity: 90,
  },
  {
    id: "d5",
    name: "Devon Williams",
    initials: "DW",
    x: 232,
    y: 405,
    ringStatus: "available",
    equipment: "flatbed",
    truckLabel: "Mack Anthem · Flatbed",
    hosRemainingHours: 8.8,
    hosMaxHours: 11,
    laneHistoryCount: 27,
    costPerMile: 1.88,
    laneFamiliarity: 79,
  },
  {
    id: "d6",
    name: "Kai Nakamura",
    initials: "KN",
    x: 226,
    y: 365,
    ringStatus: "en_route",
    equipment: "dry_van",
    truckLabel: "International LT · Dry",
    hosRemainingHours: 7.1,
    hosMaxHours: 11,
    laneHistoryCount: 22,
    costPerMile: 1.91,
    laneFamiliarity: 45,
    currentLoadEndingInHours: 4.5,
    enRoutePath: [
      { x: Math.round(AZ.flag.x), y: Math.round(AZ.flag.y) },
      { x: 224, y: 382 },
      { x: Math.round(AZ.phx.x), y: Math.round(AZ.phx.y) },
    ],
  },
  {
    id: "d7",
    name: "Aisha Brown",
    initials: "AB",
    x: 235,
    y: 392,
    ringStatus: "unavailable",
    equipment: "reefer",
    truckLabel: "Freightliner · Reefer (shop)",
    hosRemainingHours: 0,
    hosMaxHours: 11,
    laneHistoryCount: 38,
    costPerMile: 2.1,
    laneFamiliarity: 66,
  },
  {
    id: "d8",
    name: "Omar Haddad",
    initials: "OH",
    x: 222,
    y: 412,
    ringStatus: "available",
    equipment: "reefer",
    truckLabel: "Kenworth · Reefer",
    hosRemainingHours: 10.2,
    hosMaxHours: 11,
    laneHistoryCount: 48,
    costPerMile: 1.79,
    laneFamiliarity: 85,
  },
  {
    id: "d9",
    name: "Lisa Park",
    initials: "LP",
    x: 225,
    y: 400,
    ringStatus: "constrained",
    equipment: "reefer",
    truckLabel: "Volvo · Reefer",
    hosRemainingHours: 3.1,
    hosMaxHours: 11,
    laneHistoryCount: 33,
    costPerMile: 1.84,
    laneFamiliarity: 70,
  },
  {
    id: "d10",
    name: "Victor Diaz",
    initials: "VD",
    x: Math.round(AZ.king.x) + 6,
    y: Math.round(AZ.king.y) + 8,
    ringStatus: "available",
    equipment: "dry_van",
    truckLabel: "Peterbilt · Dry",
    hosRemainingHours: 9,
    hosMaxHours: 11,
    laneHistoryCount: 12,
    costPerMile: 1.99,
    laneFamiliarity: 40,
  },
  {
    id: "d11",
    name: "Grace Kim",
    initials: "GK",
    x: 230,
    y: 403,
    ringStatus: "en_route",
    equipment: "flatbed",
    truckLabel: "Mack · Flatbed",
    hosRemainingHours: 5.5,
    hosMaxHours: 11,
    laneHistoryCount: 29,
    costPerMile: 1.87,
    laneFamiliarity: 58,
    currentLoadEndingInHours: 1.2,
    enRoutePath: [
      { x: 224, y: 410 },
      { x: 230, y: 403 },
      { x: 236, y: 396 },
    ],
  },
  {
    id: "d12",
    name: "Nate Collins",
    initials: "NC",
    x: 234,
    y: 399,
    ringStatus: "available",
    equipment: "dry_van",
    truckLabel: "Freightliner · Dry",
    hosRemainingHours: 8,
    hosMaxHours: 11,
    laneHistoryCount: 35,
    costPerMile: 1.8,
    laneFamiliarity: 74,
    hasActiveConflict: true,
  },
  {
    id: "d13",
    name: "Brianna Holt",
    initials: "BH",
    x: 229,
    y: 396,
    ringStatus: "off_duty",
    equipment: "flatbed",
    truckLabel: "Western Star · Flatbed",
    hosRemainingHours: 0,
    hosMaxHours: 11,
    laneHistoryCount: 41,
    costPerMile: 1.76,
    laneFamiliarity: 82,
  },
  {
    id: "d14",
    name: "Frank O'Neil",
    initials: "FO",
    x: 220,
    y: 388,
    ringStatus: "available",
    equipment: "reefer",
    truckLabel: "Kenworth · Reefer",
    hosRemainingHours: 9.8,
    hosMaxHours: 11,
    laneHistoryCount: 51,
    costPerMile: 1.77,
    laneFamiliarity: 91,
  },
  {
    id: "d15",
    name: "Miguel Santos",
    initials: "MS",
    x: Math.round(AZ.yuma.x) - 4,
    y: Math.round(AZ.yuma.y) + 6,
    ringStatus: "constrained",
    equipment: "dry_van",
    truckLabel: "Volvo · Dry",
    hosRemainingHours: 4,
    hosMaxHours: 11,
    laneHistoryCount: 24,
    costPerMile: 1.83,
    laneFamiliarity: 63,
  },
];
